# DX 601 Week 9 Homework

## Introduction

In this homework, you will practice basic operations with vectors and matrices.

## Example Code

You may find it helpful to refer to this GitHub repository of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx500-examples
* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Shared Imports

Do not install or use any additional modules.
Installing additional modules may result in an autograder failure resulting in zero points for some or all problems.

In [70]:
import math
import sys

In [71]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

## Problems

### Problem 1

Set `p1` to the vector from calculating $[0.0, 0.3, 0.65] + [2.2, 6.2, 0.35]$.

In [3]:
# YOUR CHANGES HERE

v1 = np.array([0.0, 0.3, 0.65])
v2 = np.array([2.2, 6.2, 0.35])

p1 = v1 + v2

In [4]:
p1

array([2.2, 6.5, 1. ])

### Problem 2

Set `p2` to the magnitude of the vector $[1, 3, 6]$?

In [5]:
# YOUR CHANGES HERE

v1 = np.array([1, 3, 6])

p2 = np.linalg.norm(v1)

In [6]:
p2

np.float64(6.782329983125268)

### Problem 3

Set `p3` to the magnitude of the vector `q3`.

In [7]:
# DO NOT CHANGE

q3 = np.asarray([5.2, 5.9, 9.1, 4.3, 2.9])
q3

array([5.2, 5.9, 9.1, 4.3, 2.9])

In [8]:
# YOUR CHANGES HERE

p3 = np.linalg.norm(q3)

In [9]:
p3

np.float64(13.098091464026353)

### Problem 4

Set `p4` to the dot product of $[2, 0, 3]$ and $[0, 4, 1]$.

Hint: this should feel like a really easy case to just do in your head.

In [10]:
# YOUR CHANGES HERE

v1 = np.array([2, 0, 3])
v2 = np.array([0, 4, 1])

p4 = v1 @ v2

In [11]:
p4

np.int64(3)

### Problem 5

Set `p5` to the element-wise product of `u5` and `v5`.

Hint: the default behavior of mathematical operations on NumPy arrays is to calculate on an element-wise basis.

In [12]:
# DO NOT CHANGE

u5 = np.asarray([5, 5, 5])
u5

array([5, 5, 5])

In [13]:
# DO NOT CHANGE

v5 = np.asarray([1, 6, 2])
v5

array([1, 6, 2])

In [14]:
# YOUR CHANGES HERE

p5 = u5 * v5

In [15]:
p5

array([ 5, 30, 10])

### Problem 6

Set `p6` to the dot product of `u6` and `v6`.

In [16]:
# DO NOT CHANGE

u6 = np.asarray([2.03, 0.40, 1.35, 9.26, 4.23])
u6

array([2.03, 0.4 , 1.35, 9.26, 4.23])

In [17]:
# DO NOT CHANGE

v6 = np.asarray([1.32, 0.96, 2.35, 1.23, 0.25])
v6

array([1.32, 0.96, 2.35, 1.23, 0.25])

In [18]:
# YOUR CHANGES HERE

p6 = u6 @ v6

In [19]:
p6

np.float64(18.6834)

### Problem 7

Set `p7` to the cosine similarity of `u7` and `v7`.

In [21]:
# DO NOT CHANGE

u7 = np.asarray([1, 1, 1, 1])
u7

array([1, 1, 1, 1])

In [22]:
# DO NOT CHANGE

v7 = np.asarray([0, 2, 0, 0])
v7

array([0, 2, 0, 0])

In [23]:
# YOUR CHANGES HERE

def cosine_similarity(a, b):
    dot_product = a @ b
    magnitude_a = np.linalg.norm(a)
    magnitude_b = np.linalg.norm(b)
    return dot_product / (magnitude_a * magnitude_b)

p7 = cosine_similarity(u7, v7)

In [24]:
p7

np.float64(0.5)

### Problem 8

Set `p8` to the vector $[x, y]$ corresponding to the polar coordinates $(r, \theta) = (1, 1)$.

In [72]:
# YOUR CHANGES HERE

r = 1
theta = 1

x = r * np.cos(theta)
y = r * np.sin(theta)

p8 = np.array([x, y])

In [73]:
p8

array([0.54030231, 0.84147098])

### Problem 9

Set `p9` to the scalar-vector product $3.1 \cdot [1.31, 2.06, 9.56, 1.79]$.

In [41]:
# YOUR CHANGES HERE

scalar = 3.1
vector = np.array([1.31, 2.06, 9.56, 1.79])

p9 = scalar * vector

In [42]:
p9

array([ 4.061,  6.386, 29.636,  5.549])

### Problem 10

Set `p10` to be a unit vector in the same direction as $[1.31, 2.13, -0.92]$.


In [43]:
# YOUR CHANGES HERE

arr = np.array([1.31, 2.13, -0.92])
magnitude = np.linalg.norm(arr)
unit_vector = arr / magnitude

p10 = unit_vector

In [44]:
p10

array([ 0.49165501,  0.79940853, -0.34528444])

### Problem 11

Set `p11` to be the first of the following vectors that is orthogonal to $[1, 0, 0]$.

* $[1, 1, 1]$
* $[0.5, 1, 1]$
* $[0, 1, 1]$
* $[1, 0, 1]$

In [48]:
v0 = np.array([1, 0, 0])
v1 = np.array([1, 1, 1])
v2 = np.array([0, 5, 1, 1])
v3 = np.array([0, 1, 1])
v4 = np.array([1, 0, 1])

print(v0 @ v1)
print(v0 @ v3)
print(v0 @ v4)

p11 = v3

1
0
1


In [49]:
p11

array([0, 1, 1])

### Problem 12

Set `p12` to the first vector in the following list which is linearly dependent on the previous vectors.

* $[0, 1, 1]$
* $[0, 0, 1]$
* $[1, 0, 1]$
* $[1, 1, 1]$

In [53]:
# YOUR CHANGES HERE

vector_arr = np.array([[0, 1, 1],
                       [0, 0, 1],
                       [1, 0, 1],
                       [1, 1, 1]])

for row in range(len(vector_arr)):
    rows_so_far = vector_arr[:row + 1]
    current_rank = np.linalg.matrix_rank(rows_so_far)
    row_rank = row + 1
    if current_rank < row_rank:
        print(f"{vector_arr[row]} is dependent")
    else:
        print(f"{vector_arr[row]} is NOT dependent")

p12 = np.array([1, 1, 1])

[0 1 1] is NOT dependent
[0 0 1] is NOT dependent
[1 0 1] is NOT dependent
[1 1 1] is dependent


In [54]:
p12

array([1, 1, 1])

### Problem 13

Set `p13` to the $3 \times 3$ identity matrix.

In [55]:
# YOUR CHANGES HERE

p13 = np.eye(3)

In [56]:
p13

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Problem 14

Set `p14` to the x intercept of the equation $3y + 5x = 2$.

In [74]:
# YOUR CHANGES HERE

p14 = 2/5

In [75]:
p14

0.4

### Problem 15

Given the dictionary of phrases and vectors in `q15`, set `p15` to the phrase (key) whose vector has the highest cosine similarity with $[0.1, 0.5, 0.2]$.

In [57]:
# DO NOT CHANGE

q15 = {
    "cat": [0.1, 0.6, 0.3],
    "dog": [0.2, 0.5, 0.1],
    "elephant": [-0.3, 0.2, 0.5],
    "giraffe": [-0.4, 0.3, -0.1],
    "lion": [0.1, 0.7, 0.2]
}
q15 = {k: np.asarray(v) for k, v in q15.items()}

q15

{'cat': array([0.1, 0.6, 0.3]),
 'dog': array([0.2, 0.5, 0.1]),
 'elephant': array([-0.3,  0.2,  0.5]),
 'giraffe': array([-0.4,  0.3, -0.1]),
 'lion': array([0.1, 0.7, 0.2])}

In [59]:
# YOUR CHANGES HERE

def cosine_similarity(a, b):
    dot_product = a @ b
    magnitude_a = np.linalg.norm(a)
    magnitude_b = np.linalg.norm(b)
    return dot_product / (magnitude_a * magnitude_b)

target_arr = np.array([0.1, 0.5, 0.2])

highest_cosine_similarity = 0
highest_cosine_similarity_key = ""
for k, v in q15.items():
    current_cosine_similarity = cosine_similarity(target_arr, v)
    if current_cosine_similarity > highest_cosine_similarity:
        highest_cosine_similarity = current_cosine_similarity
        highest_cosine_similarity_key = k

p15 = highest_cosine_similarity_key

In [60]:
p15

'cat'

### Problem 16

Rescale the vectors $[2, 0, 0, 0]$ and $[0, 1, 1, 1]$ so that they are orthonormal.

Save the first rescaled vector in `p16a` and the second rescaled vector in `p16b`.

In [65]:
# YOUR CHANGES HERE

v1 = np.array([2, 0, 0, 0])
v2 = np.array([0, 1, 1, 1])

print(v1 @ v2)

p16a = v1 / np.linalg.norm(v1)

0


In [62]:
p16a

array([1., 0., 0., 0.])

In [63]:
# YOUR CHANGES HERE

p16b = v2 / np.linalg.norm(v2)

In [64]:
p16b

array([0.        , 0.57735027, 0.57735027, 0.57735027])

### Problem 17

Set `p17` to the result of the matrix multiplication of `x17` by `y17`.

Hint: NumPy has a function for matrix multiplication, and also overrides the Python @ operator.

In [31]:
# DO NOT CHANGE

x17 = np.array([[0.2, 3.1, 0.6], [-2.9, 2.3, 4.2], [3.0, 4.5, 1.7]])
x17

array([[ 0.2,  3.1,  0.6],
       [-2.9,  2.3,  4.2],
       [ 3. ,  4.5,  1.7]])

In [32]:
# DO NOT CHANGE

y17 = np.array([[1, 2, 3], [6, 5, 4], [7, 8, 9]])
y17

array([[1, 2, 3],
       [6, 5, 4],
       [7, 8, 9]])

In [33]:
# YOUR CHANGES HERE

p17 = x17 @ y17

In [34]:
p17

array([[23. , 20.7, 18.4],
       [40.3, 39.3, 38.3],
       [41.9, 42.1, 42.3]])

### Problem 18

Set `p18` to the angle $\theta$ between the vectors in `u18` and `v18`.
Use the measure of the angle in radians, not degrees.

Hint: you can use the cosine similarity to calculate $\mathrm{cos}~\theta$.
The inverse cosine function to recover the measure of the angle is often called the arc cosine, and both the math and NumPy modules use this for their naming.

In [66]:
# DO NOT CHANGE

u18 = np.asarray([0.3, 0.2, 0.9, -0.4])
u18

array([ 0.3,  0.2,  0.9, -0.4])

In [67]:
# DO NOT CHANGE

v18 = np.asarray([-0.1, 0.3, 0.6, -0.2])
v18

array([-0.1,  0.3,  0.6, -0.2])

In [76]:
# YOUR CHANGES HERE

def angle_between_vector(v1, v2):
    dot_product = v1 @ v2
    magnitude_a = np.linalg.norm(v1)
    magnitude_b = np.linalg.norm(v2)

    cosine_theta = dot_product / (magnitude_a * magnitude_b)

    return np.arccos(cosine_theta)

p18 = angle_between_vector(u18, v18)

In [77]:
p18

np.float64(0.5023368499123668)

### Problem 19

Set `p19` to be the largest magnitude vector from the following list.

* $[0.1, 0.3, 0.9, -0.8]$
* $[0.2, 0.2, 0.7, 0.6]$
* $[-0.2, 0.2, 0.7, -0.6]$
* $[1.0, 1.0, 0.4, 0.5]$

In [36]:
# YOUR CHANGES HERE

v1 = [0.1, 0.3, 0.9, -0.8]
v2 = [0.2, 0.2, 0.7, 0.6]
v3 = [-0.2, 0.2, 0.7, -0.6]
v4 = [1.0, 1.0, 0.4, 0.5]

print(np.linalg.norm(v1))
print(np.linalg.norm(v2))
print(np.linalg.norm(v3))
print(np.linalg.norm(v4))

p19 = v4

1.2449899597988734
0.9643650760992954
0.9643650760992954
1.5524174696260025


In [37]:
p19

[1.0, 1.0, 0.4, 0.5]

### Problem 20

Set `p20` to $3 \mathbf{x} + 5$ where $x$ is stored in `x20`.

In [38]:
# DO NOT CHANGE

x20 = np.asarray([0.2, 0.5, -0.3, 0.8])

In [39]:
# YOUR CHANGES HERE

def find_x(x):
    return 3 * x + 5

p20 = find_x(x20)

In [40]:
p20

array([5.6, 6.5, 4.1, 7.4])

### Generative AI Usage

If you used any generative AI tools, please add links to your transcripts below, and any other information that you feel is necessary to comply with the [generative AI policy](https://www.bu.edu/cds-faculty/culture-community/gaia-policy/).
If you did not use any generative AI tools, simply write NONE below.

YOUR ANSWER HERE

Problem 8
* I wasn’t sure how to work with polar and cartesian coordinates together. I learned how to convert from polar to cartesian coordinates and that you had to use np.cos for x every time and np.sin for y every time.
* https://chatgpt.com/share/68f648ed-8140-800d-97a0-e108f5c2a4d5

Problem 12
* I wasn’t sure how to find when the vector was dependent. I knew that I had to use np.linalg.matrix_rank after some googling, but wasn’t sure what to do after that.
* https://chatgpt.com/share/68f7a3f2-c6d0-800d-b085-e0f78ea42450

Problem 16
* I didn’t know how to find the orthonormal. I realized that the vectors were already orthogonal so all I had to do was normalize them.
* https://chatgpt.com/share/68f7a58b-0c10-800d-a3e6-59752a5d3ed2